var Roblox ={"CurrentUser":'https://assetgame.roblox.com/Game/GetCurrentUser.ashx',"Mobileuser":'http://roblox.com/mobileapi/userinfo','GitHub':'https://github.com/Junkiebox/RobloxEnhancer/wiki/Updates-And-Features','Items':'http://assetgame.roblox.com/asset/?id=311113132','Following':'https://roblox.com/users/friends/list-json?pageSize=500&imgWidth=110&imgHeight=110&imgFormat=png&friendsType=Following&userId=','unreadmessages':'https://roblox.com/messages/api/get-my-unread-messages-count'}
var Storage = {Set:function(a){chrome.storage.sync.set(a)},Get:function(a,b){chrome.storage.sync.get(a,b)}}
$.fn.add=function(attr,attr2){this.attr(attr,attr2);};
$.fn.style=function(sty){var options=$.extend({set:""},sty);this.attr("style",options.set);};
function Notify(ico,BoxTitle,bod,tag,button,run){chrome.notifications.create(tag,{type:"basic",buttons:[{title:button}],iconUrl:ico,title:BoxTitle,message:bod});(function(){return run.go})()}
if(chrome.notifications){chrome.notifications.onButtonClicked.addListener(function(id){(id=="1")?window.open("https://github.com/Junkiebox/RobloxEnhancer/wiki/Updates-And-Features"):(id=="2")?window.open("https://roblox.com/my/messages/#!/inbox"):(id=="3")?window.open("https://roblox.com/My/Money.aspx#/#TradeCurrency_tab"):(id=='4')?chrome.storage.sync.get('link',function(url){window.open(url.link)}):(id=='5')?window.open('https://github.com/Junkiebox/RobloxEnhancer/wiki/Updates-And-Features'):'' });}
function ToolTip(func,msg){$(".tooltip").text(msg);$(func).hover(function(){$(".tooltip").fadeIn();},function(){$(".tooltip").fadeOut();}).mousemove(function(e){$(".tooltip").css({left:e.pageX-50,top:e.pageY+20});});}
function QuickPost(id,Post){var Link="https://forum.roblox.com/Forum/AddPost.aspx?PostID="+id; $.get(Link).success(function(Data){var VS=Data.match(/id="__VIEWSTATE" value="(.+)"/)[1];var EV=Data.match(/id="__EVENTVALIDATION" value="(.+)"/)[1];$.ajax({url:Link,type:"post",data:{__VIEWSTATE:VS,__EVENTVALIDATION:EV,"ctl00$cphRoblox$Createeditpost1$PostForm$PostBody":Post,"ctl00$cphRoblox$Createeditpost1$PostForm$PostButton":"Post"},complete:function(response){document.write(response.responseText);chrome.storage.sync.get('obc',function(c){(c.obc) ? $('head').append('<link rel="stylesheet" type="text/css" href="'+chrome.extension.getURL("css/obc.css")+'" >'):''})},error:function(){ alert('Error occured, if you\'re underage, quick post wont work. :(');}});})}
var friends={"token":function token(tok){$.get("https://roblox.com/Empty.aspx").success(function(e){tok(e.match(/Roblox\.XsrfToken\.setToken\('(.+)'\);/)[1]);});},"unfollow":function(userId,token){$.ajax({url:"https://api.roblox.com/user/unfollow",type:"POST",data:JSON.stringify({followedUserId:userId}),headers:{"X-CSRF-TOKEN":token},contentType:"application/json"});},"follow":function(userId){friends.token(function(ken){$.ajax({url:"https://api.roblox.com/user/follow",type:"POST",data:JSON.stringify({followedUserId:userId}),headers:{"X-CSRF-TOKEN":ken},contentType:"application/json"});});}};
$.fn.extend({check:function(){this.prop('checked',true)},uncheck:function(){this.prop('checked',false)}})
$.fn.insertAtCaret=function(t){return this.each(function(){document.selection&&"TEXTAREA"==this.tagName?(this.focus(),sel=document.selection.createRange(),sel.text=t,this.focus()):this.selectionStart||"0"==this.selectionStart?(startPos=this.selectionStart,endPos=this.selectionEnd,scrollTop=this.scrollTop,this.value=this.value.substring(0,startPos)+t+this.value.substring(endPos,this.value.length),this.focus(),this.selectionStart=startPos+t.length,this.selectionEnd=startPos+t.length-1,this.scrollTop=scrollTop):(this.value+=t,this.focus(),this.value=this.value)})};