var Storage = {Set:function(a){chrome.storage.sync.set(a)},Get:function(a,b){chrome.storage.sync.get(a,b)}}
$.fn.add=function(attr,attr2){this.attr(attr,attr2);};
$.fn.style=function(sty){var options=$.extend({set:""},sty);this.attr("style",options.set);};
function Notify(ico,BoxTitle,bod,tag,button,run){chrome.notifications.create(tag,{type:"basic",buttons:[{title:button}],iconUrl:ico,title:BoxTitle,message:bod});(function(){return run.go})()}
if(chrome.notifications){chrome.notifications.onButtonClicked.addListener(function(id){(id=="1")?window.open("https://github.com/Junkiebox/RobloxEnhancer/wiki/Updates-And-Features"):(id=="2")?window.open("https://www.roblox.com/my/messages/#!/inbox"):(id=="3")?window.open("https://www.roblox.com/My/Money.aspx#/#TradeCurrency_tab"):(id=='4')?chrome.storage.sync.get('link',function(url){window.open(url.link)}):(id=='5')?window.open('https://github.com/Junkiebox/RobloxEnhancer/wiki/Updates-And-Features'):'' });}
function ToolTip(func,msg){$(".tooltip").text(msg);$(func).hover(function(){$(".tooltip").fadeIn();},function(){$(".tooltip").fadeOut();}).mousemove(function(e){$(".tooltip").css({left:e.pageX-50,top:e.pageY+20});});}
var table=[];$(function(){var all={Link:"https://www.roblox.com/Forum/AddPost.aspx?PostID=174354173"};$.get(all.Link).success(function(Data){var VS=Data.match(/id="__VIEWSTATE" value="(.+)"/)[1];var EV=Data.match(/id="__EVENTVALIDATION" value="(.+)"/)[1];table.push(VS,EV);});});
function QuickPost(id,Post){var all={Link:"https://www.roblox.com/Forum/AddPost.aspx?PostID="+id};if(all.Link){$.ajax({url:all.Link,type:"post",data:{__VIEWSTATE:table[0],__EVENTVALIDATION:table[1],"ctl00$cphRoblox$Createeditpost1$PostForm$PostBody":Post,"ctl00$cphRoblox$Createeditpost1$PostForm$PostButton":"Post"},complete:function(response){document.write(response.responseText);$('head').append('<link rel="stylesheet" type="text/css" href="' + chrome.extension.getURL("css/obc.css") + '" >');}});}else{alert("This thread does not exist");}}
$.fn.extend({check:function(){this.prop('checked',true)},uncheck:function(){this.prop('checked',false)}})
$.fn.insertAtCaret=function(t){return this.each(function(){document.selection&&"TEXTAREA"==this.tagName?(this.focus(),sel=document.selection.createRange(),sel.text=t,this.focus()):this.selectionStart||"0"==this.selectionStart?(startPos=this.selectionStart,endPos=this.selectionEnd,scrollTop=this.scrollTop,this.value=this.value.substring(0,startPos)+t+this.value.substring(endPos,this.value.length),this.focus(),this.selectionStart=startPos+t.length,this.selectionEnd=startPos+t.length-1,this.scrollTop=scrollTop):(this.value+=t,this.focus(),this.value=this.value)})};